### ISSUE TITLE
Add a wiki or at least some keymaps to the Readme?

### ISSUE THREAD

**Issue by Mcpower03** [pappasam/coc-jedi#10]
So I would like to use this in place of jedi-vim and coc-python, this plugin already does autocomplete just fine, but goto definition is kinda fuzzy. Within jedi-vim the keybind is leader-g, but I cant find docs on how to do it here. So maybe some documentation would be nice

**Comment by pappasam** [comment]
I'd love to help with this, but `coc-jedi` is a `coc.nvim` extension; it is not responsible for creating or managing your `coc.nvim` keymappings.

`coc.nvim` is an LSP client that provides all mappings that you may want to use. For an example on mapping keys, please refer to `coc.nvim`'s documentation here: https://github.com/neoclide/coc.nvim#example-vim-configuration
