### ISSUE TITLE
Fresh install can't use jedi

### ISSUE THREAD

**Issue by windowsrefund** [pappasam/coc-jedi#12]
I've got the coc-jedi exension installed along with python-language-server but see this when I open a .py file. 

`[coc.nvim]: UnhandledRejection: Launching server "jedi" using command jedi-language-server failed.`

I'd like to better understand what this error means since I suspect it has to do with the jedi pip package and yet, I saw no mention of that as a requirements when installing the pieces mentioned above. In any case, I have the package installed and see a ~/.local/lib/python3.7/site-packages/jedi which is not in my $PATH. Is that the issue here? Trying to understand best practices...

Here's the section from coc-settings.json. Please let me know if there's any additional information I should add and thanks in advance for any assistance 

```

  "jedi.executable.command": "jedi-language-server",
  "jedi.enable": true,
  "jedi.markupKindPreferred": "plaintext",
  "jedi.trace.server": "messages",
  "jedi.jediSettings.autoImportModules": [],
  "jedi.executable.args": [],
  "jedi.completion.disableSnippets": false,
  "jedi.diagnostics.enable": true,
  "jedi.diagnostics.didChange": true,
  "jedi.diagnostics.didSave": true,
```

**Comment by pappasam** [comment]
Given your configuration, you'll need to also install [jedi-language-server](https://github.com/pappasam/jedi-language-server). jedi-language-server wraps jedi in a language server.

Alternatively, you can remove the line ` "jedi.executable.command": "jedi-language-server",` and coc-jedi will manage the installation for you.

**Comment by windowsrefund** [comment]
As mentioned in the original comment, I already have jedi-language-server installed and in my $PATH

**Comment by windowsrefund** [comment]
Overcame this with the following steps. Still unclear why related documentation seems to skip right past this stuff.

1. Install python3-venv package using OS package manager 
2. Remove previously installed python-language-server package
3. Remove "jedi.executable.command" config from coc-settings.json
4. Restart neovim to allow it to install python-language-server
