### ISSUE TITLE
No completion for numpy

### ISSUE THREAD

**Issue by astier** [pappasam/coc-jedi#13]
### Minimal vimrc

```vim
call plug#begin($XDG_DATA_HOME.'/nvim/plugins')
    Plug 'neoclide/coc.nvim', { 'branch': 'release' }
call plug#end()
let g:coc_global_extensions = ['coc-jedi']
```

### Steps to reproduce

1. `nvim bug.py`
2. Enter instertmode
3. Type `import nu`

`numpy` is not shown in the completion-menu.

### Expected behavior

`numpy` should show up in the completion-list if `import nu` is typed.

**Comment by pappasam** [comment]
Questions to help us debug:

- Which Python version / distribution are you using? 3.8, conda, etc?
- Do you have numpy installed in that distribution?

**Comment by pappasam** [comment]
Also, see this issue: https://github.com/pappasam/jedi-language-server/issues/27 Maybe you can find a work-around there.

**Comment by astier** [comment]
I reinstalled everything from again and it works now. Thank you.

**Comment by astier** [comment]
I was wrong. I still had the issue. I just forgot to uninstall coc-python which completed numpy. After uninstalling coc-python the bug appeared again. Installing jedi-language-server manually with pip and setting

```
"jedi.executable.command": "~/.local/bin/jedi-language-server"
```

solved the issue for me.

I am using arch-linux and installed numpy from the arch repos. It seems like coc-jedi is not able to find it.

**Comment by astier** [comment]
https://github.com/pappasam/coc-jedi/issues/4 seems to be related.

**Comment by pappasam** [comment]
Yep, jedi tries to be smart about figuring out your environment, but given the diversity of Python environments, somethings you just have to manage the jedi / jedi-language-server installation yourself (and put it in the same environment as your dependencies). Glad we figured out a solution for you and hopefully Jedi keeps getting smarter over time!

**Comment by astier** [comment]
So its an issue of jedi and not coc-jedi?

**Comment by pappasam** [comment]
That's what I suspect, but I'm not certain either way at present.

**Comment by astier** [comment]
Should we reopen this issue or do you want to leave it at that?

**Comment by pappasam** [comment]
Let's leave this closed. Other open issues address the underlying problem and I've updated the readme to document the current workaround: https://github.com/pappasam/coc-jedi#no-completion--goto-definition-while-using-conda-homebrew-asdf-etc
