### ISSUE TITLE
Get import-error even when autocompletion works

### ISSUE THREAD

**Issue by prmammoth** [pappasam/coc-jedi#21]
I have a few python module imports on top of my module. I am on python 3.8, and use a virtualenv. jedi-language-server is installed in virtualenv and the virtualenv is active on shell. coc-jedi is installed through CocInstall coc-jedi.
Modules have been installed through 

`pip install -r Requirements.txt`
Some packages are used as
-e packageName 
in Requirements.txt
regular python packages work fine. modules from current package work fine. Those installed as -e packageName work partially. I see autocompletion work sometimes and sometimes not. However I see a consistent error like this though for anything installed as -e packageName
[
![Screenshot from 2021-01-24 21-06-02](https://user-images.githubusercontent.com/4122734/105635272-0fe28a00-5e88-11eb-8ce2-cc4840e29f3b.png)
](url)
The error is import-error: Unable to import CommonConstant.apiConst

Am I missing some configuration or is it a genuine bug. Let me know if any other information is needed.

**Comment by pappasam** [comment]
Thanks for your issue! Would you be able to provide an example codebase with the characteristics you describe? A link to a GitHub repo will suffice. This will help me debug your issue!

**Comment by pappasam** [comment]
Closing due to lack of additional detail.
