### ISSUE TITLE
High cpu usage for pylint

### ISSUE THREAD

**Issue by matheusfillipe** [pappasam/coc-jedi#33]
pyling is getting called too often which is causing a way too high cpu usage on my machine.
Would it be possible to call it only once back to normal mode? I am using the same coc-config.json that are here: https://github.com/pappasam/coc-jedi#additional-diagnostics

OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

**Comment by matheusfillipe** [comment]
Well I switched to flake8 and it works much better now. In case someone wants to know the relevant config on coc-settings.json:

```json
  "diagnostic-languageserver.linters": {
    "flake8": {
      "sourceName": "flake8",
      "command": "flake8",
      "debounce": 200,
      "rootPatterns": [".git", "pyproject.toml", "setup.py"],
      "args": ["--ignore=E402,C901,W503,W504,E116,E702,C0103,C0114,C0115,C0116,C0103,C0301,W0613,W0102,R0903,R0902,R0914,R0915,R0205,W0703,W0702,W0603,E30", "--format=%(row)d,%(col)d,%(code).1s,%(code)s: %(text)s", "-" ],
      "offsetLine": 0,
      "offsetColumn": 0,
      "formatLines": 1,
      "formatPattern": [
        "(\\d+),(\\d+),([A-Z]),(.*)(\\r|\\n)*$",
        {
          "line": 1,
          "column": 2,
          "security": 3,
          "message": 4
        }
      ],
      "securities": {
        "W": "info",
        "E": "warning",
        "F": "info",
        "C": "info",
        "N": "hint"
      }
    }
  },
  "diagnostic-languageserver.filetypes": {
    "python": "flake8",
     ...

```

**Comment by pappasam** [comment]
Awesome, either I, or you (through PR) can add this to the readme. I'll do it by end of week, but if you submit a PR I'll merge right away. Once it's in there, I think we can consider this closed!
