### ISSUE TITLE
Getting errors on opening - completion works fine

### ISSUE THREAD

**Issue by JDuchniewicz** [pappasam/coc-jedi#35]
Hello, I switched from `coc-python` to `coc-jedi` and I keep receiving these errors on startup:

```
coc.nvim]: /bin/sh: line 1: /home/jduchniewicz/.config/coc/extensions/node_modules/coc-jedi/.venv/bin/jedi-language-server: No such file or directory
[coc.nvim] jedi: installing jedi-language-server==0.30.2 in "/home/jduchniewicz/.config/coc/extensions/node_modules/coc-jedi/.venv"
[coc.nvim]: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
[coc.nvim]: WARNING: You are using pip version 20.2.3; however, version 21.1 is available.
[coc.nvim]: You should consider upgrading via the '/home/jduchniewicz/.config/coc/extensions/node_modules/coc-jedi/.venv/bin/python3 -m pip install --upgrade pip' command.
[coc.nvim] jedi: Error: Command failed: python3 -m venv /home/jduchniewicz/.config/coc/extensions/node_modules/coc-jedi/.venv && /home/jduchniewicz/.config/coc/extensions/node_modules/coc-jedi/.venv/bin/pip install -U pip jed
i-language-server==0.30.2
```

The completion works fine apart from that.

**Comment by ctnguyenvn** [comment]
the same error with neovim-0.4.4/python3.6
```
[coc.nvim] jedi: Error: Command failed: python3 -m venv /root/.config/coc/extensions/node_modules/coc-jedi/.venv && /root/.config/coc/extensions/node_modules/coc-jedi/.venv/bin/pip install -U pip jedi-language-server==0.34.1
[coc.nvim] Server jedi failed to start: Launching server "jedi" using command jedi-language-server failed
```

**Comment by pappasam** [comment]
@JDuchniewicz @ctnguyenvn I think the stand-out line is the following:

`[coc.nvim]: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`

The error you mention is probably related to your environment and pip's implicit usage of `--user` within virtualenvs. I'd refer to the following resources to debug:

- https://github.com/microsoft/vscode-python/issues/14327
- https://stackoverflow.com/questions/30604952/pip-default-behavior-conflicts-with-virtualenv

Please let me know if you figure out the solution that works for your environment and I'll add it to the readme!

**Comment by AlefCS** [comment]
> @JDuchniewicz @ctnguyenvn I think the stand-out line is the following:
> 
> `[coc.nvim]: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`
> 
> The error you mention is probably related to your environment and pip's implicit usage of `--user` within virtualenvs. I'd refer to the following resources to debug:
> 
> * [ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv. microsoft/vscode-python#14327](https://github.com/microsoft/vscode-python/issues/14327)
> * https://stackoverflow.com/questions/30604952/pip-default-behavior-conflicts-with-virtualenv
> 
> Please let me know if you figure out the solution that works for your environment and I'll add it to the readme!

Hi @pappasam, [this comment](https://github.com/microsoft/vscode-python/issues/14327#issuecomment-757408341) says to change the value of `include-system-site-packages` to `true` in `pyvenv.cfg` and apparently it worked for some people. But the `venv` is recreated with `false` every time I reopen vim, so I'm not being able to test it. Do you know how to change this permanently?

**Comment by pappasam** [comment]
Should be generally resolved by: https://github.com/pappasam/coc-jedi/commit/18458a9c13f00e63ab9d884e876b89330d3dfaea
