### ISSUE TITLE
Conflict with easymotion  https://github.com/easymotion/vim-easymotion

### ISSUE THREAD

**Issue by androidfans** [pappasam/coc-jedi#42]
![image](https://user-images.githubusercontent.com/6452650/127260799-56fa20df-a1ac-4d09-af78-fb9a71c72292.png)

**Comment by pappasam** [comment]
Is this [coc-jedi](https://github.com/pappasam/coc-jedi)-specific? Or is this a general [coc](https://github.com/neoclide/coc.nvim) conflict?

**Comment by pappasam** [comment]
@androidfans confirmed that this is an issue with `coc.nvim`. Please refer to this issue for potential resolutions: <https://github.com/neoclide/coc.nvim/issues/110>
