### ISSUE TITLE
How I can set limit for number of suggestions?

### ISSUE THREAD

**Issue by vando2108** [pappasam/coc-jedi#44]

**Comment by pappasam** [comment]
This is not supported. As far as I can tell, it is up to coc.nvim itself to determine how many suggestions are displayed to the end user. For example, you might have multiple language servers / coc extensions running at the same time, all of whom are providing coc.nvim completion options (coc-yank, coc-sources, etc). If you'd like to figure out how to limit the number of suggestions, I'd raise the issue in coc.nvim.
