### ISSUE TITLE
How to prevent the coc-jedi from showing the function docstring automatically?

### ISSUE THREAD

**Issue by Wei-Mao** [pappasam/coc-jedi#53]
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/51208983/160231518-a6e8e0af-699d-4639-bb2b-08b2db0f54ee.png">

**Comment by pappasam** [comment]
`coc-jedi` is not responsible for this. Look into `coc.nvim`'s `*signature.enable*` option in your `coc-settings.json` and set this value to false. My configuration (which accomplishes what you're requesting):
```json
{
  "signature.hideOnTextChange": true,
  "signature.enable": false
}
```

**Comment by Wei-Mao** [comment]
> I don't believe `coc-jedi` is not responsible for this. Look into `coc.nvim`'s `signature.enable` option in your `coc-settings.json` and set this value to false. My configuration (which accomplishes what you're requesting):
> 
> ```json
> {
>   "signature.hideOnTextChange": true,
>   "signature.enable": false
> }
> ```

Hi! Thanks a lot! Your configuration in `coc-settings.json` works as expected.
