### ISSUE TITLE
Explanation of Benefits over Coc-Python

### ISSUE THREAD

**Issue by jkroes** [pappasam/coc-jedi#7]
For those of us who have used Jedi in combination with LSP but don't have much technical knowledge about the two, could you maybe explain some of the differences from the other COC extension promoted by coc.nvim?

**Comment by pappasam** [comment]
I haven't used `coc-python` in a long while, so I'm not up to speed on the benefits (if any) that `coc-jedi` currently has over `coc-python`. From a technical perspective:

- `coc-jedi` is a wrapper around `jedi-language-server` while `coc-python` is a fork of Microsoft's vscode Python extension
- `jedi-language-server` wraps jedi in a language server, while `coc-python` forks a language server that wraps a bunch of Python utilities (see here: https://github.com/Microsoft/vscode-python#feature-details )

Basically, over the past year or 2, I've had some frustration combating 3rd party dependencies / using the latest version of jedi my language server of choice, so I implemented my own language server. `coc-jedi` makes that language server easy to use with `coc.nvim`.

See [here](https://github.com/pappasam/jedi-language-server#inspiration) for an explanation of jedi-language-server's inspiration.

If you notice any benefits over the latest version of `coc-python`, I'd love to hear about them / add them to the readme! If not, please close this issue if I've answered your question sufficiently.

**Comment by jkroes** [comment]
Thank you! I recently switched back to Emacs/Evil recently, but I've been comparing the LSP packages/plugins for both editors to find the areas where they can learn from each other. I'll have to spend more time with coc-jedi when I can find the time.
