### ISSUE TITLE
The result of omitted jedi.executable.command is unexpected for README

### ISSUE THREAD

**Issue by kevinhwang91** [pappasam/coc-jedi#8]
If `jedi.executable.command` is omitted, `coc-jedi` always download `jedi-language-server` in venv in *unix system.

Here is the source code about this issue.

https://github.com/pappasam/coc-jedi/blob/6e178d83ed1ea2f756ae293d4aa67f1324749811/src/jlsExecutable.ts#L58-L70

I have no ability to create a PR because I have no idea about TS and I haven't developed any plugins about coc.

**Comment by pappasam** [comment]
Updated the docs to reflect what's actually happening, resolved in 188a0f40acfd204e4eadac562d4d7f9a29dd18f6
